$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

display_name: dev-ml-template-pipeline
experiment_name: dev-ml-template-pipeline
description: dev-ml-template-pipeline

settings:
  default_compute: azureml:cpu-cluster


jobs:
  component_preprocess:
    type: command
    component: azureml://registries/dev-ml-template-registry103/components/dev_ml_template_preprocess/versions/1
    inputs:
      data_input:
        type: uri_folder
        path: azureml:dev-ml-template:1
    outputs:
      data_output:
        mode: rw_mount
    limits: 
      timeout: 360
  component_train:
    type: command
    component: azureml://registries/dev-ml-template-registry103/components/dev_ml_template_train/versions/1
    inputs:
      data_input: ${{parent.jobs.component_preprocess.outputs.data_output}}
    outputs:
      model_output:
        type: mlflow_model
        mode: rw_mount
    limits:
      timeout: 360
  component_predict:
    type: command
    component: azureml://registries/dev-ml-template-registry103/components/dev_ml_template_predict/versions/1
    inputs:
      data_input: ${{parent.jobs.component_preprocess.outputs.data_output}}
      model_input: ${{parent.jobs.component_train.outputs.model_output}}
    outputs:
      predict_output:
        mode: rw_mount
    limits:
      timeout: 360
  component_evaluate:
    type: command
    component: azureml://registries/dev-ml-template-registry103/components/dev_ml_template_evaluate/versions/1
    inputs:
      data_input: ${{parent.jobs.component_preprocess.outputs.data_output}}
      predict_input: ${{parent.jobs.component_predict.outputs.predict_output}}
    limits:
      timeout: 360